name: Shared Deploy Workflow

on:
  workflow_call:
    inputs:
      site_url:
        description: 'The base URL to prepend to paths'
        required: false
        default: 'https://notes.biolab.si/'
        type: string
    secrets:
      SSH_KEY:
        required: true


jobs:
  deploy:
    name: ${{ github.event_name == 'push' && 'Deployment' || 'Test deployment' }}
    runs-on: ubuntu-latest
    outputs:
      captured_urls: ${{ steps.deploy.outputs.urls }}
    env:
      DEPLOY_SERVER: 193.2.72.46
      DEPLOY_USER: biolab

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - name: Trigger deploy script over SSH
        id: deploy
        run: |
          ARGS=""
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            ARGS="${{ github.head_ref }}"
          fi
          ssh -o StrictHostKeyChecking=yes $DEPLOY_USER@$DEPLOY_SERVER "${{ github.repository }}" $ARGS > full_output.txt
          SITE="${{ inputs.site_url }}"
          # grep finds links, sed replaces prefix, tr flattens,
          # xargs trims the result if there are not results and tr adds a trailing space
          # || true is necessary because grep return exit code 1 when it finds nothing
          URLS=$(grep '^#LINK#' full_output.txt | sed "s|^#LINK#|$SITE|" | tr '\n' ' ' | xargs || true)
          echo "urls=$URLS" >> $GITHUB_OUTPUT

          grep -v '^#LINK#' full_output.txt || true

  check-links:
    name: Broken links checker
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && needs.deploy.outputs.captured_urls != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: biolab/notes-deploy-ci

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright & Chromium
        run: |
          npm install playwright
          npx playwright install chromium --with-deps

      - name: Run Link Checker
        run: node .github/scripts/check-links.js ${{ needs.deploy.outputs.captured_urls }}
